# Positive definite, Positive semi-definite #

In [2]:
import numpy as np

I = np.eye(3) # Positive definite
A = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]]) # Positive definite
R = np.array([[1,1],[1,1]]) # Positive semi-definite

# Norm(entrywise matrix norm) #

In [9]:
S = (np.arange(9) -4).reshape((3,3))
print(np.linalg.norm(S))

7.745966692414834


In [58]:
T = np.eye(3)
print(np.linalg.norm(S+T) <= np.linalg.norm(S) + np.linalg.norm(T)) # For Any S,T
print(np.linalg.norm(S@T) <= np.linalg.norm(S) * np.linalg.norm(T)) # For Any S,T

True
True


# Trace #

In [20]:
np.trace(I)

3.0

In [57]:
print(np.trace(T@A), np.trace(A@T))

6.0 6.0


In [56]:
x = np.array([[1],[2],[3]])
print(np.trace(x.T@A@x), np.trace(A@x@x.T),np.trace(x@x.T@A))

12 12 12


# Determinant

In [43]:
print(np.linalg.det(A))

4.0


In [71]:
print(np.linalg.det(I))

1.0


In [112]:
T = np.array([[2,1,0],[-1,2,-1],[3,-1,2]])
try:
    B = np.linalg.inv(T)
    print(B)
    print(np.linalg.det(T @ B))
except LinAlgErr as err:
    print("DET = 0")


[[ 0.6 -0.4 -0.2]
 [-0.2  0.8  0.4]
 [-1.   1.   1. ]]
0.9999999999999999


# Eigen vector & Eigen value #

In [14]:
B = np.array([[2,3],[2,1]])
W, E = np.linalg.eig(B)
v = e.T
for i in [0,1]:
    print(W[i],E[i])
    print(B @ v[i] == W[i] * v[i])

4.0 [ 0.83205029 -0.70710678]
[ True  True]
-1.0 [0.5547002  0.70710678]
[ True  True]


# Diagonalization #

In [34]:
E2 = np.linalg.inv(E)

T = E @ np.diag(W) @ E2
print(T)

[[2. 3.]
 [2. 1.]]
