In [15]:
import numpy as np
x = np.array([1,2,3])
y = np.array([[1,2,3]])
z = np.array([[1],[2],[3]])
print(x @ x)
print(x @ x.T)
print(x.T @ x)

print(y.T @ y)
print(y @ y.T)
# error: print(y.T @ y.T)  print(y @ y)

print(z.shape == y.T.shape)

14
14
14
[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[14]]
True
