In [4]:
import tensorflow as tf
import numpy as np

x = tf.placeholder(tf.float32,shape=[None,2])

e = np.random.sample((3,6,2))
data = tf.data.Dataset.from_tensor_slices(e)
iterator = data.make_one_shot_iterator()
next = iterator.get_next()


print(data.output_types, data.output_shapes)
with tf.Session() as sess:
    while True:
        try:
            print(sess.run(next))
        except tf.errors.OutOfRangeError as e:
            #print(e)
            break
'''

train, test = tf.keras.datasets.mnist.load_data()
train_x, train_y = train
dataset= tf.data.Dataset.from_tensor_slices(({''}))'''

<dtype: 'float64'> (6, 2)
[[0.17963245 0.98931571]
 [0.59111266 0.23756936]
 [0.669817   0.44565537]
 [0.6358869  0.75883842]
 [0.41192549 0.66907452]
 [0.86011117 0.72121809]]
[[0.30162359 0.96948549]
 [0.07165584 0.77310141]
 [0.94517898 0.13442299]
 [0.82465908 0.64551759]
 [0.21361131 0.35730504]
 [0.57122559 0.44016527]]
[[0.92894687 0.47291438]
 [0.72087374 0.53759049]
 [0.90498777 0.57324243]
 [0.81652923 0.57132046]
 [0.83997816 0.46655559]
 [0.32231256 0.12568778]]


"\n\ntrain, test = tf.keras.datasets.mnist.load_data()\ntrain_x, train_y = train\ndataset= tf.data.Dataset.from_tensor_slices(({''}))"